# Generated by Django 3.1.7 on 2021-03-19 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_auto_20210316_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='last_date_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last update'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name'),
        ),
    ]
